### ISSUE TITLE
create timestamp

### ISSUE THREAD

**Issue by sulphite** [fac31/Jana-Reza-Bot#5]
- [x] decide if this should be a slash command or something else like the bot reading everyone's messages
- [x] install day.js

**IF SLASH COMMAND:** 

- [x] register a command name and description. Something like `/time`, takes one argument, the user can write a time in natural language (e.g. "tomorrow at 6pm") and bot will convert it to a timestamp
- [x] find out if we can get user's time zone from their command message
- [x] convert the relative time into an absolute time
- [x] convert that into formatted timestamp
- [x] post this in the channel
- MAYBE: bot says "i'm going to create your event `<EVENT TITLE>` at `<TIMESTAMP>`. Is that ok?" with yes/no buttons. That's a new ticket though.
- BONUS: add an extra command where users can configure how the timestamp is formatted (long date with day of week, just numbers, etc)

**OTHERWISE**

honestly i don't know if an alternative is feasible. bot would have to read messages until it notices use of a date. then it would have to work out if that was just irrelevant chat, or people actually trying to organise something. Maybe through call to chatgpt. but this could end up being way too many calls

**Comment by RGHANILOO** [comment]
I believe it would be most effective to initiate the process with a `/`command` as you suggested for the following reasons, especially when considering integration with Discord and OpenAI:

- When the user enters the slash command, we can prompt them for input
- User will input a specific time in `<natural language>`
- User will then be asked to provide a title and brief description
- ChatGPT API will generate content based on the user's input
- User will be asked to confirm, and Discord will finalize the card
- Additionally, it would be beneficial to incorporate a reminder feature that alerts users 15-30 minutes before the scheduled event
- We can incorporate multiple slash commands to retrieve different types of information

I agree that having ChatGPT continuously active may incur high costs and present programming challenges in determining when to trigger a response or activity.
